name: finalprojects8
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.4.5
  flutter_markdown: ^0.7.7
  animate_do: ^4.2.0
  confetti: ^0.8.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_auth_web: ^5.8.14
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cloud_firestore: ^5.6.7
  pdf: ^3.11.2
  path_provider: ^2.0.14
  flutter_highlight: ^0.7.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  shared_preferences: ^2.2.2
  highlight_text: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  # This ensures the Material Icons font is included with your application.
  uses-material-design: true
  assets:
    - lib/images/default_profile.jpg
    - lib/images/bk.jpg
    - lib/images/bk1.jpg
    - lib/images/background.png
    - lib/images/bk2.jpg
    - lib/images/py_machine.jpg
    - lib/images/py1.jpg
    - lib/images/py2.jpg
    - lib/images/pyth.jpg
  # To add custom fonts to your application, add a fonts section here.
  # For example:
  # fonts:
  #- family: Schyler
  #  fonts:
  #    - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  #       fonts:


