// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCr_jILAHqhL4C46zHbsVelrmRTXJqxYU',
    appId: '1:625753930820:web:f12fa8fe54f00c41971011',
    messagingSenderId: '625753930820',
    projectId: 'codequest-7e54f',
    authDomain: 'codequest-7e54f.firebaseapp.com',
    storageBucket: 'codequest-7e54f.firebasestorage.app',
    measurementId: 'G-CLKY1K6VH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxkc2icZW4-GOJFAdAxIe0YTVZPxAYMA',
    appId: '1:625753930820:android:4fb6a24a55ff59d3971011',
    messagingSenderId: '625753930820',
    projectId: 'codequest-7e54f',
    storageBucket: 'codequest-7e54f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd4CTccJkDDzL0BzONrcu9AfGPjDzjLLc',
    appId: '1:625753930820:ios:8b4d302520e11892971011',
    messagingSenderId: '625753930820',
    projectId: 'codequest-7e54f',
    storageBucket: 'codequest-7e54f.firebasestorage.app',
    iosBundleId: 'com.example.finalprojects8',
  );
}
